/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CartRouteImport } from './routes/cart'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as SearchRouteImport } from './routes/search'
import { Route as OrderIdRouteImport } from './routes/order.$id'
import { Route as RecoveryIdRouteImport } from './routes/recovery.$id'
import { Route as RestaurantIdRouteImport } from './routes/restaurant.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderIdRoute = OrderIdRouteImport.update({
  id: '/order/$id',
  path: '/order/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoveryIdRoute = RecoveryIdRouteImport.update({
  id: '/recovery/$id',
  path: '/recovery/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantIdRoute = RestaurantIdRouteImport.update({
  id: '/restaurant/$id',
  path: '/restaurant/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/orders': typeof OrdersRoute
  '/search': typeof SearchRoute
  '/order/$id': typeof OrderIdRoute
  '/recovery/$id': typeof RecoveryIdRoute
  '/restaurant/$id': typeof RestaurantIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/orders': typeof OrdersRoute
  '/search': typeof SearchRoute
  '/order/$id': typeof OrderIdRoute
  '/recovery/$id': typeof RecoveryIdRoute
  '/restaurant/$id': typeof RestaurantIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/orders': typeof OrdersRoute
  '/search': typeof SearchRoute
  '/order/$id': typeof OrderIdRoute
  '/recovery/$id': typeof RecoveryIdRoute
  '/restaurant/$id': typeof RestaurantIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cart'
    | '/orders'
    | '/search'
    | '/order/$id'
    | '/recovery/$id'
    | '/restaurant/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/orders'
    | '/search'
    | '/order/$id'
    | '/recovery/$id'
    | '/restaurant/$id'
  id:
    | '__root__'
    | '/'
    | '/cart'
    | '/orders'
    | '/search'
    | '/order/$id'
    | '/recovery/$id'
    | '/restaurant/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CartRoute: typeof CartRoute
  OrdersRoute: typeof OrdersRoute
  SearchRoute: typeof SearchRoute
  OrderIdRoute: typeof OrderIdRoute
  RecoveryIdRoute: typeof RecoveryIdRoute
  RestaurantIdRoute: typeof RestaurantIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/$id': {
      id: '/order/$id'
      path: '/order/$id'
      fullPath: '/order/$id'
      preLoaderRoute: typeof OrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recovery/$id': {
      id: '/recovery/$id'
      path: '/recovery/$id'
      fullPath: '/recovery/$id'
      preLoaderRoute: typeof RecoveryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurant/$id': {
      id: '/restaurant/$id'
      path: '/restaurant/$id'
      fullPath: '/restaurant/$id'
      preLoaderRoute: typeof RestaurantIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CartRoute: CartRoute,
  OrdersRoute: OrdersRoute,
  SearchRoute: SearchRoute,
  OrderIdRoute: OrderIdRoute,
  RecoveryIdRoute: RecoveryIdRoute,
  RestaurantIdRoute: RestaurantIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
